### PR TITLE
webring: ensure directory for generated files exist

### PR DESCRIPTION
**Pull request by norrland**

### CODE REVIEW

**Comment by lawik** [comment]
Oh, thanks :D

Would you mind editing it to use https://hexdocs.pm/elixir/File.html#mkdir_p!/1 instead? I don't see much use for the case where it fails to create the directory and returns the error tuple in this case.

Curious what brought you into checking out and **running** this repo :)
Also, sweet username.

**Comment by norrland** [comment]
> Oh, thanks :D
> 
> Would you mind editing it to use https://hexdocs.pm/elixir/File.html#mkdir_p!/1 instead? I don't see much use for the case where it fails to create the directory and returns the error tuple in this case.
Done.
> 
> Curious what brought you into checking out and **running** this repo :)
> Also, sweet username.

New to Elixir, been digging around for some examples on serving static html content. Found a bunch of your repos interesting.
So when testing this one out I found the issue with the directory. :+1:

**Comment by lawik** [comment]
Cool, feel free to get in touch at underjord.io or my Twitter if you have any troubles on tour learning journey :)

Now if we could just get rid of that `with` entirely since the mkdir_p! will either blow up or do the job I should be able to merge this :)

**Comment by norrland** [comment]
> Cool, feel free to get in touch at underjord.io or my Twitter if you have any troubles on tour learning journey :)
> 
> Now if we could just get rid of that `with` entirely since the mkdir_p! will either blow up or do the job I should be able to merge this :)

Will do!

**Comment by lawik** [comment]
Thanks for the PR. Much appreciated :)

**Pull request merged**
