### PR TITLE
Create keathley.txt

### PR DESCRIPTION
**Pull request by keathley**
Lemme know if I did anything incorrectly here.

### CODE REVIEW

**Comment by lawik** [comment]
Woo! I'll adjust if there's something wrong :) Welcome aboard.

**Comment by lawik** [comment]
All good, but your site is missing

```
<link rel="alternate" type="application/rss+xml" href="https://underjord.io/feed.xml" />
```

**Comment by keathley** [comment]
Oh good call. Should be fixed now.

**Comment by lawik** [comment]
It is!

**Pull request merged**
